### ISSUE TITLE
[Insight] Source code should not contain TODO comments - in depfile.yml, line 16

### ISSUE THREAD

**Issue by joshavg** [laniger/OmgDb#37]
**[in depfile.yml, line 16](https://github.com/joshavg/OmgDb/blob/93cb832c2b51c7864dc7318ea712527646c1b4da/depfile.yml#L16)**

> TODO comments are left in the code when a feature (or a bug) isn't completely developed (or fixed). You should complete the implementation and remove the comment.

```
    collectors:
      - type: bool
        must:
          - type: className
            regex: AppBundle\\Entity\\Repository\\.+
        # TODO remove me
        must_not:
          - type: className
            regex: AppBundle\\Entity\\Repository\\DateFactory
  - name: Service
    collectors:
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/b6908968-5877-4940-9bfe-4a0ed3e39cc7/analyses/27)_
